### ISSUE TITLE
 Unable to decode a number on path

### ISSUE THREAD

**Issue by barnabasbusa** [optimism-java/hildr#197]
Latest hildr bug reproducable with kurtosis - optimism-package
```
11:19:57.205 [main] DEBUG i.m.c.u.i.l.InternalLoggerFactory trace_id= span_id= trace_flags= Using SLF4J as the default logging framework
io.optimism.config.ConfigLoadException: org.github.gestalt.config.exceptions.GestaltException: Failed getting config path: config, for class: io.optimism.config.Config
 - level: ERROR, message: Unable to decode a number on path: config.chainConfig.systemConfig.l1FeeScalar, from node: LeafNode{value='452312848583266388373324160190187140051835877600158453279134670530344387928'} attempting to decode BigInteger
 - level: MISSING_VALUE, message: Unable to find node matching path: config.chainConfig.systemConfig.l1FeeScalar, for class: SystemConfig, during record decoding
	at io.optimism.config.Config.create(Config.java:134)
	at io.optimism.cli.Cli.toConfig(Cli.java:206)
	at io.optimism.cli.Cli.run(Cli.java:168)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.optimism.Hildr.main(Hildr.java:32)
```

**Comment by GrapeBaBa** [comment]
@barnabasbusa What is origin of the value `452312848583266388373324160190187140051835877600158453279134670530344387928 `, it seems there is a space character at last.

**Comment by GrapeBaBa** [comment]
@barnabasbusa should be fixed by #199

**Comment by barnabasbusa** [comment]
Do you auto build to "latest"? 
I still seem to have the same problem

**Comment by GrapeBaBa** [comment]
> Do you auto build docker images to "latest"? I still seem to have the same problem

We haven't build a new latest docker image yet. We are testing [Granite](https://specs.optimism.io/protocol/granite/overview.html) hardfork, will release a new version once finished. It should be very soon.

**Comment by GrapeBaBa** [comment]
@barnabasbusa Released. Can you try again?
